#!/usr/bin/env ruby

require "rus3"

opts = {}

while ARGV.size > 0
  arg = ARGV.shift
  case arg
  when "-d", "--debug"
    opts[:debug] = true
  when "-v", "--version"
    puts "rus3 version #{Rus3::VERSION} (#{Rus3::RELEASE})"
    exit 0
  end
end

Rus3::Repl.start(verbose: opts[:debug])
